### PR TITLE
Revise panel

### LINKED ISSUE #683: The width of the panel covers the list on the left completely
The width of the panel covers the list on the left completely, by design should leave (at least at max width) space to the left to select other apps/units/machines:

### LINKED ISSUE #685: Panel with semi-transparent background
The background behind the panel seems to get semitransparent:
Screenshot 2020-09-16 at 14 08 48

This panel is not a modal, so there shouldn't be any background when the panel is open

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

- Reduce panel to 60% of viewport width
- Enable background interaction when a panel is open

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- View model details
- Click a model with more than one app
- Panel will open - should be 60% of viewport
- Click another app under panel and see panel content change

## Details

Fixes #685, Fixes #683

### CODE REVIEW

**Comment by clagom** [comment]
Great! Works very well. Just a comment on the active state when you select an app.
Now it's like this:
Screenshot 2020-09-22 at 11 55 57

Should be like this:
Screenshot 2020-09-22 at 11 55 54
So that users know what is selected

**Comment by barrymcgee** [comment]
@clagom I've added the active state here.

**Review by hatched — APPROVED** [review]

**Comment by hatched** [comment]
While not related to this branch I found an issue qa'ing it: https://github.com/canonical-web-and-design/jaas-dashboard/issues/692

**Comment by clagom** [comment]
@spencerbygraves can you please check design wise, UX and interactions look good thanks @barrymcgee

**Comment by spencerbygraves** [comment]
Thanks @barrymcgee looks good.

**Pull request merged**
