### PR TITLE
Reduce models icon width to 14px

### LINKED ISSUE #306: The updated models icon is the wrong size
The models icon is stretched vertically. The actual size is 16px wide x 14px high.

image

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

Reduce models icon width to 14px

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Verify models icon is 16x14px

## Details

Fixes #306

### CODE REVIEW

**Comment by spencerbygraves** [comment]
@barrymcgee this has fixed the models icon, but now the other two are too small.

The models one is slightly different as the actual size is 16px wide x 14px high.

Thanks.

**Comment by barrymcgee** [comment]
@spencerbygraves In that case, the solution is to reset export the models icon in a 16 x 16 frame but leaving whitespace top and bottom. Can you link that updated asset here and I'll drop it in?

**Comment by spencerbygraves** [comment]
@barrymcgee try this...

[icon-models.svg.zip](https://github.com/canonical-web-and-design/jaas-dashboard/files/4166491/icon-models.svg.zip)

**Comment by hatched** [comment]
It looks like the logo is 1, maybe 2 pixels too high on a retina.

Screen Shot 2020-02-07 at 9 40 09 AM

**Pull request merged**
