### PR TITLE
Add Framer Motion and add little animation to Login box

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

Add Framer Motion and add little animation to Login box

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Refresh page and verify little login zoom animation

### CODE REVIEW

**Comment by hatched** [comment]
looks great, love how it adds some life to the app. It would be even better if it would work on the whole login box and not just the content in it though.

**Comment by hatched** [comment]
Looks much better 👍 

If you felt so inclined those login snapshots should be removed and replaced with actual assertions. The size of these login snapshot tests are totally useless for asserting a failure.

QA Issue:

The login mask never goes away after logging in on JAAS.

**Comment by hatched** [comment]
### Size & build time comparison
<details>
  <summary>Before framer-motion: 302.37 KB @ 55.23s</summary>
  File sizes after gzip:

  302.37 KB (+36.92 KB)  build/static/js/2.1b486564.chunk.js
  36.76 KB (+10.58 KB)   build/static/css/main.0231c149.chunk.css
  23.29 KB (-1.02 KB)    build/static/js/main.f9e06ab1.chunk.js
  7.5 KB (+7.27 KB)      build/static/css/2.2a61ec7a.chunk.css
  779 B                  build/static/js/runtime-main.13ba7e39.js
</details>

<details>
  <summary>After framer-motion: 329.98 KB @ 62.08s</summary>
  329.98 KB (+27.62 KB)  build/static/js/2.caf2f5fe.chunk.js
  36.75 KB (-10 B)       build/static/css/main.f338b6ac.chunk.css
  23.36 KB (+73 B)       build/static/js/main.66dfbb05.chunk.js
  7.5 KB                 build/static/css/2.2a61ec7a.chunk.css
  779 B                  build/static/js/runtime-main.13ba7e39.js
</details>

#### Delta 27.61 KB @ 6.85s

**Review by hatched — APPROVED** [review]

**Comment by hatched** [comment]
Looks great, it's smoother in Chrome than in Firefox but looks the best in Safari 😄

**Review by spencerbygraves — CHANGES_REQUESTED** [review]
@barrymcgee thanks for trying this. To be honest I'm not keen on the bounce aspect of the animation, it doesn't feel like it matches the other animations we have, on the panels for example.

Is it possible to try a version without that bounce? So a simpler fade up maybe.

@long-chung please add any thoughts if you have them.

Thanks.

**Comment by long-chung** [comment]
Agree with Spencer (Sorry Barry). Simple fade in and up feels nicer

**Pull request merged**
