### PR TITLE
Fail silently if we're unable to make a fullStatus request.

### LINKED ISSUE #1088: App crashes if fullStatus returns an error
In the event that the model poller's `fullStatus` call returns an unrecoverable error the application crashes. 

Error handling for this call was not implemented as the generated schema didn't indicate it as a possibility. 
ref: https://bugs.launchpad.net/juju/+bug/1936004

### PR DESCRIPTION
**Pull request by hatched**
## Done

Add a simple check if there is an error in the `fullStatus` call in the API. 

This code will be removed in the near future in favor of the watchers.

## QA

- Does the model list load?

## Details

Fixes #1088

### CODE REVIEW

**Review by huwshimi — APPROVED** [review]

**Comment by cristinadresch** [comment]
@cassiocassio could you check if this has fixed your issue?

**Comment by cassiocassio** [comment]
Still fails for me

Screenshot 2021-07-21 at 11 01 12

https://jaas-dashboard-1089.demos.haus/models

perhaps authentication related tho':

{request-id: 1,…}
request-id: 1
response: {bakery-discharge-required: {caveats: [{cid: "time-before 2021-07-21T11:01:49.076976082Z"}, {,…}],…},…}
bakery-discharge-required: {caveats: [{cid: "time-before 2021-07-21T11:01:49.076976082Z"}, {,…}],…}
discharge-required-error: "macaroon discharge required: authentication required"

**Comment by cristinadresch** [comment]
@hatched any thoughts?

**Comment by hatched** [comment]
We'll need to wait until @cassiocassio and I are able to pair on this to track down the issue as this patch should have resolved the original one.

**Comment by cristinadresch** [comment]
@hatched you are both back now so can you schedule something please

**Pull request closed without merging**
