### PR TITLE
Show the model status using real data

### PR DESCRIPTION
**Pull request by hatched**
## Done

Show the model status details on the model details page. 

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Click on a model you own and it should show your model status.
- Navigate back to the model listing and click on a model you don't own. It should also show you the model status.

## Details

- Requires #70 to land first (contains code from #70).
- This is unstyled, that will be able to be done as a follow-up.

### CODE REVIEW

**Comment by hatched** [comment]
Good find @barrymcgee I've resolved the issue, it's ready for another qa.

**Comment by barrymcgee** [comment]
Testing locally:

This is my list of models:

Screenshot 2019-10-09 at 10 01 19

One of my models `mongodb-test` continues to be empty. Even if this was expected, I'd want to see an error/info message instead of empty tables?

Screenshot 2019-10-09 at 09 59 48

The `monitor` and `test-model` models populate the first two tables but not the third? Is this because the third table represents relational data as it is shared?

If so, I'd expect this table to disappear for those models rather than render empty?

Screenshot 2019-10-09 at 10 01 56

The shared models _do_ populate all three tables.

Screenshot 2019-10-09 at 10 04 59

**Comment by anthonydillon** [comment]
Instead of hiding tables I would suggest we should display a message in the empty table to the user.

**Comment by clagom** [comment]
> Instead of hiding tables I would suggest we should display a message in the empty table to the user.

+1

**Comment by clagom** [comment]
Btw this is generally what we do also on RBAC and other products, I think it's safe to assume it should be the default behaviour whenever we can

**Pull request merged**
