### PR TITLE
Correct status label capitalisation

### LINKED ISSUE #187: The status column titles have lost their capitalisation
Created from PR comment: https://github.com/canonical-web-and-design/jaas-dashboard/pull/184#pullrequestreview-312617554

image

### PR DESCRIPTION
**Pull request by barrymcgee**
Fixes #187

## Done

Correct status label capitalisation

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Status in table headers should be uppercase, all others should be capitalised.

### CODE REVIEW

**Comment by spencerbygraves** [comment]
Thanks @barrymcgee. @anthonydillon, this was for table column headers, we shouldn't be capitalising messages.

**Comment by barrymcgee** [comment]
@anthonydillon I'm confused - this change only applies the class to strings wrapped with a status icon - where are you seeing it applied to longer messages?

**Comment by anthonydillon** [comment]
@barrymcgee its applied to the Messages column in the machines table at the bottom on the model details page.

**Comment by hatched** [comment]
Looks like after updating to master this needs the snapshot updated again.

**Comment by barrymcgee** [comment]
@anthonydillon Ok, gotcha - but that is unrelated to any change in this PR. 

However, I have now made that change also.

**Pull request merged**
