### PR TITLE
Remove double border on table rows

### LINKED ISSUE #185: App table has double lines
The horizontal lines in the app table are duplicated:

image

It should match the model listing.

Thanks

### PR DESCRIPTION
**Pull request by barrymcgee**
Fixes #185

## Done

Remove double border on table rows

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Verify that double borders on table rows ahve been removed.

### CODE REVIEW

**Comment by anthonydillon** [comment]
@barrymcgee I can't work out what this is trying to do. I can't see a difference between the table borders on this PR and on master. Could you give more info or a screenshot please.

**Comment by spencerbygraves** [comment]
@barrymcgee thanks, looks good 👍

**Comment by barrymcgee** [comment]
@anthonydillon This is to remove double borders on item rows.

Before: 

Screenshot 2019-11-07 at 12 12 12


After: 

Screenshot 2019-11-07 at 12 12 33

**Comment by barrymcgee** [comment]
@anthonydillon Issue created in Vanilla https://github.com/canonical-web-and-design/vanilla-framework/issues/2628

**Pull request merged**
