### PR TITLE
Improve the responsive navigation styling

### LINKED ISSUE #890: Navigation - Implement small screen considerations
Designs: https://zpl.io/29XlWne

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Improve the responsive navigation styling

## QA
- Load model details
- Scale your screen too small screen
- See that the header section matches [the new small-screen designs](https://zpl.io/bL6rrnY).

## Details
Fixes #890 

## Screenshots
image

### CODE REVIEW

**Comment by long-chung** [comment]
- [ ] Remove the right chevron
- [ ] Active state missing
- [ ] Could we use the full width of the mobile screen? If not no biggie
- [ ] Anyway to hide the scrollbar?

**Comment by anthonydillon** [comment]
> Anyway to hide the scrollbar?

Unfortunately not without removing the ability to scroll.

**Review by hatched — APPROVED** [review]

**Comment by barrymcgee** [comment]
@anthonydillon `scrollbar-width: none;` will hide it on most browsers.

**Comment by anthonydillon** [comment]
@barrymcgee thanks, my concern is by removing any indication to the user that is a scrollable element will lead to weak UX.

**Pull request merged**
