### PR TITLE
Improve share error handling

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

Improve share error handling

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Register a dud controller
- Try to add/remove/amend users in model share menu
- Verify that error toast appears

### CODE REVIEW

**Comment by anthonydillon** [comment]
@barrymcgee can you expand on how to "Register a dud controller", please.

**Comment by barrymcgee** [comment]
@anthonydillon Just a controller you know will fail - a controller that doesn't exist - e.g. 255.0.0.0

**Comment by anthonydillon** [comment]
Oh change it in the local config. I remember now.

**Comment by anthonydillon** [comment]
The UI doesn't load when it can't connect to a true controller.
image

**Comment by anthonydillon** [comment]
I get this in Firefox:
```
Firefox can’t establish a connection to the server at wss://255.0.0.0/api. client.ts:104
-- 
error { target: WebSocket, isTrusted: true, srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
unable to log into controller cannot connect WebSocket:  
Array(4) [ "wss://255.0.0.0/api", undefined, {…}, true ]
```

**Review by anthonydillon — APPROVED** [review]
Code and QA :+1:

**Comment by anthonydillon** [comment]
Huge improvement for users registering controllers

**Pull request merged**
