### PR TITLE
Add missing colored icons

### LINKED ISSUE #133: Details page: Model details statuses aren't coloured
Screen Shot 2019-10-30 at 4 35 56 PM

### LINKED ISSUE #161: Status icons are the wrong size
The status icons should be 8x8, currently they are too big.

image

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

- Add missing colored icons
- Reduce size of icons

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Check out the all new icons

## Details

Fixes #161, Fixes #133

### CODE REVIEW

**Comment by hatched** [comment]
Why does this PR contain dependency updates?

**Comment by hatched** [comment]
QA Issue:

The unknown entity is off line.
Screen Shot 2019-11-01 at 11 35 01 AM

**Comment by spencerbygraves** [comment]
@barrymcgee it's no longer a circle...

image

**Comment by barrymcgee** [comment]
@spencerbygraves Created a separate issue here https://github.com/canonical-web-and-design/jaas-dashboard/issues/171

**Pull request merged**
