### PR TITLE
Show the controller version in the controller view

### LINKED ISSUE #554: Version is not shown with self-bootstrapped controller
When viewing the controllers page with Juju 2.8 the version column on the controller page is empty 

Screen Shot 2020-06-15 at 3 49 37 PM

### PR DESCRIPTION
**Pull request by hatched**
## Done

The controller version wasn't shown when connected to a self-bootstrapped Juju controller. This adds that data.

## QA

- Pull code
- Have the Juju 2.8 snap installed and bootstrap a new controller on your choice of cloud.
- Follow the setup instructions for a [Juju qa](https://github.com/canonical-web-and-design/jaas-dashboard#connecting-a-local-dashboard-to-a-remote-controller)
- See the controller page for the version.

## Details

Fixes #554 

## Screenshots

Screen Shot 2020-06-30 at 1 50 10 PM

### CODE REVIEW

**Comment by barrymcgee** [comment]
Can you add a test for this please?

**Comment by barrymcgee** [comment]
@hatched Did you say you wanted to follow up with tests on this one?

**Comment by hatched** [comment]
Yeah, the juju index file is untested so to setup the scaffolding to test that will be quite a bit of work so I'd prefer it not block this.

**Comment by hatched** [comment]
I'm closing this branch and including the change in my active branch.

**Pull request closed without merging**
